In [1]:
import pandas as pd
import time
import datetime
from datetime import date
import pandas_datareader.data as web

symbols = ['^GSPC', '^DJI', 'FB', 'AMZN', 'TSLA', 'GOOGL', 'MSFT']

start = datetime.date(2007, 1, 1)

end = datetime.date.today()

data = {}
for i in symbols:
    try:
        data[i] = web.DataReader(i, 'yahoo', start, end)
        data[i].insert(0,'Symbol',i)
        print ('Done', i)
    except :
        print('No information for ticker: {}'.format(i))
        continue

/Users/patrickfahy99/opt/anaconda3/lib/python3.7/site-packages/pandas_datareader/compat/__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

Done ^GSPC
Done ^DJI
Done FB
Done AMZN
Done TSLA
Done GOOGL
Done MSFT

In [2]:
data[symbols[0]]

,Symbol,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,,
2007-01-03,^GSPC,1429.420044,1407.859985,1418.030029,1416.599976,3429160000,1416.599976
2007-01-04,^GSPC,1421.839966,1408.430054,1416.599976,1418.339966,3004460000,1418.339966
2007-01-05,^GSPC,1418.339966,1405.750000,1418.339966,1409.709961,2919400000,1409.709961
2007-01-08,^GSPC,1414.979980,1403.969971,1409.260010,1412.839966,2763340000,1412.839966
2007-01-09,^GSPC,1415.609985,1405.420044,1412.839966,1412.109985,3038380000,1412.109985
...,...,...,...,...,...,...,...
2020-08-06,^GSPC,3351.030029,3318.139893,3323.169922,3349.159912,4267490000,3349.159912
2020-08-07,^GSPC,3352.540039,3328.719971,3340.050049,3351.280029,4104860000,3351.280029
2020-08-10,^GSPC,3363.290039,3335.439941,3356.040039,3360.469971,4318570000,3360.469971
2020-08-11,^GSPC,3381.010010,3326.439941,3370.340088,3333.689941,5087650000,3333.689941
2020-08-12,^GSPC,3383.209961,3355.459961,3355.459961,3382.939941,1079460423,3382.939941

In [3]:
import sqlite3

for i in range(len(symbols)):
    
    try:
        conn = sqlite3.connect('financialdata.db')
        data[symbols[i]].to_sql(symbols[i].replace('^', ''), conn, if_exists='replace', schema='financialdata.db', index=True)
    
    except:
        print('Error for {}'.format(symbols[i]))
        continue

/Users/patrickfahy99/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:2663: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,

In [8]:
c = conn.cursor()
c.execute('''
    SELECT sql
    DESCRIBE FB
    ''')

OperationalError: near "FB": syntax error